---
device_type_mappings:
  FC430: "poweredge-fc430"
  FC630: "poweredge-fc630"
  FC830: "poweredge-fc830"

device_role_mappings:
  Server: "server"
  Chassis: "server-chassis"

device_slot_mappings:
  1A: "slot-1a"
  1B: "slot-1b"
  1C: "slot-1c"
  1D: "slot-1d"
  2A: "slot-2a"
  2B: "slot-2b"
  2C: "slot-2c"
  2D: "slot-2d"
  3A: "slot-3a"
  3B: "slot-3b"
  3C: "slot-3c"
  3D: "slot-3d"
  4A: "slot-4a"
  4B: "slot-4b"
  4C: "slot-4c"
  4D: "slot-4d"
  1: "slot-1"
  2: "slot-2"
  3: "slot-3"
  4: "slot-4"
