---
# Validation
- name: Check that variables are defined
  ansible.builtin.fail:
    msg: "Variable '{{ item }}' is not defined"
  with_items:
    - nb_type
    - nb_role
    - nb_cluster
    - ansible_host
    - nb_host
    - nb_token
    - nb_site
    - nb_tenant
    - nb_tenant_tag
    - nb_rack
  when: item not in vars

# Update device
- name: Device
  netbox.netbox.netbox_device:
    netbox_url: "{{ nb_host }}"
    netbox_token: "{{ nb_token }}"
    data:
      name: "{{ inventory_hostname }}"
      device_type: "{{ device_type_mappings[nb_type] }}"
      device_role: "{{ device_role_mappings[nb_role] }}"
      cluster: "{{ nb_cluster | lower }}"
      oob_ip: "{{ ansible_host }}"
      rack: "{{ nb_rack | lower }}"
      face: "front"
      site: "{{ nb_site }}"
      tenant: "{{ nb_tenant }}"
      tags:
        - "{{ nb_tenant_tag }}"
    state: present

# Set device position
- name: Device Position in Rack
  netbox.netbox.netbox_device:
    netbox_url: "{{ nb_host }}"
    netbox_token: "{{ nb_token }}"
    data:
      name: "{{ inventory_hostname }}"
      position: "{{ nb_u }}"
    state: present
  when: nb_role == "Server" and nb_slot is not defined and nb_parent is not defined

# Set parent/child
- name: Parent Relation
  netbox.netbox.netbox_device_bay:
    netbox_url: "{{ nb_host }}"
    netbox_token: "{{ nb_token }}"
    data:
      device: "{{ nb_parent }}"
      installed_device: "{{ inventory_hostname }}"
      name: "{{ nb_slot_mappings[nb_slot] }}"
    state: present
  when: nb_role == "Server" and nb_slot is defined
